#!/bin/bash

set -e

QEMU="qemu-system-x86_64"

MAINPID=$(pgrep -f ${QEMU})
VCPU_CORES="10 42 11 43"
OTHER_CORES="12,13,44,45"
QTHREADS="-q ${OTHER_CORES}"
WATCH="no"

echo "qemu_pid=${MAINPID}"
echo "setting cpufreq governor to performance"
sudo cpupower frequency-set --governor performance &> /dev/null

while getopts 'qw' OPTION; do
	case "$OPTION" in
	q)
		QTHREADS=""
		;;
	w)
		WATCH="yes"
		;;
	?)
		echo "script usage: $(basename \$0) [-q] [-w]" >&2
		exit 1
		;;
  esac
done

shift "$(($OPTIND -1))"


sudo qemu-affinity $MAINPID -p "${OTHER_CORES}" ${QTHREADS} -i *:"${OTHER_CORES}" -w *:"${OTHER_CORES}" -k ${VCPU_CORES}

if [[ "${WATCH}" == "yes" ]]; then
	watch  ps -T -o pid,psr,comm -p ${MAINPID}
fi
