#!/bin/bash

IMAGE="${VM_CLI_IMAGE_PATH}"
KERNEL="${VM_CLI_KERNEL_PATH}"
QEMU="qemu-system-x86_64"
BACKGROUND="-nographic"
SERIAL="-serial mon:stdio"

while getopts 'qk:' OPTION; do
	case "$OPTION" in
	q)
		BACKGROUND="-daemonize"
		SERIAL="-display none"
		;;
	k)
		KERNEL="$OPTARG"
		;;
	?)
		echo "script usage: $(basename \$0) [-q] [-k <kernel_path>]" >&2
		exit 1
		;;
  esac
done
shift "$(($OPTIND -1))"

echo "kernel_path=${KERNEL:?} image_path=${IMAGE:?}"

"${QEMU}" \
	"${BACKGROUND}" \
	-enable-kvm \
	-s -machine accel=kvm \
	-smp cores=4 \
	-cpu host,+topoext \
	-name kps-vm,debug-threads=on \
	-device e1000,netdev=net0 \
	-netdev user,id=net0,hostfwd=tcp::5555-:22 \
	-append console="ttyS0,115200 root=/dev/sda rw nokaslr systemd.unit=multi-user.target isolcpus=2,3" \
	-m 4G \
	-drive if=none,id=hd,file="${IMAGE}",format=raw \
	-device virtio-scsi-pci,id=scsi \
	-device scsi-hd,drive=hd \
	-device virtio-rng-pci,max-bytes=1024,period=1000 \
	-qmp tcp:localhost:4444,server,nowait \
	${SERIAL} \
	-kernel ${KERNEL}

#	-smp sockets=1,cores=4,threads=2 \
